version: 2
updates:
- package-ecosystem: gradle
  directory: "/"
  schedule:
    interval: weekly
    day: friday
  open-pull-requests-limit: 99
  ignore:
  - dependency-name: io.fabric8:kubernetes-client
    versions:
    - 5.0.1
    - 5.0.2
    - 5.1.0
    - 5.1.1
  - dependency-name: joda-time:joda-time
    versions:
    - 2.10.9
  - dependency-name: org.apache.commons:commons-lang3
    versions:
    - "3.11"
